spring:
  cloud: #配置读取配置 读取github(云)上的配置
    config:
      uri: http://localhost:8888
      name: itoken-admin
      label: master
      profile: dev

#spring:
#  application:
#    name: itoken-admin
#  zipkin: #服务链路追踪地址
#    base-url: http://localhost:9411
#
#server:
#  port: 8084
#
#management: #健康检查配置 每个项目中都应该配置一个健康检查
#  endpoint:
#    health:
#      show-details: always
#  endpoints:
#    web:
#      exposure:
#        include: health , info #health,info  健康检查参数
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/